<?php 
$jsextra = array_key_exists('jsextra', $this->vars)? $this->jsextra : '';
?>

<div class="container mt-4" id="iem-footer">
  <hr />
  <div class="float-end">
    <form method="get" action="https://www.google.com/search" name="search" class="d-inline-flex align-items-center">
      <input value="weather.im" name="sitesearch" type="hidden" />
      <div class="me-2">
        <label for="inputsearch" class="form-label mb-0 me-2">Search Site with Google</label>
        <input type="text" class="form-control d-inline-block w-auto" name="q" id="inputsearch" placeholder="Enter search term">
      </div>
    </form>
  </div>
  <div>
    Copyright &copy; 2013-<?php echo date("Y"); ?>, Iowa State University of Science and Technology.<br />
    All rights reserved.
    <i class="bi bi-telephone"></i> <a href="https://mesonet.agron.iastate.edu/info/contacts.php">contact us</a>
    <i class="bi bi-tools"></i> <a href="https://github.com/akrherz/weather.im">development</a>
    <i class="bi bi-exclamation-triangle"></i> <a href="/disclaimer.php">disclaimer</a>
  </div>
</div><!-- /.iem-footer -->

    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/vendor/jquery/1.11.3/jquery-1.11.3.min.js"></script>
    <script src="/vendor/bootstrap/5.3.6/js/bootstrap.bundle.min.js"></script>
    <script src="/vendor/jquery-ui/1.11.4/jquery-ui.min.js"></script>
    <?php echo $jsextra; ?>
  </body>
</html>
