<?php 
if (isset($this)){
	$THISPAGE = array_key_exists('thispage', $this->vars)? $this->thispage : 'xxx-xxx';
} else{
	$THISPAGE = isset($THISPAGE) ? $THISPAGE: 'xxx-xxx';
}
$_pages = Array(
	"apps" => Array(
		"title" => "Applications", 
		"subs" => Array(
			"map" => Array("title" => "Live Application", "url" => "/live/")
		),
	),
);
?>
<div class="container" id="iem-header">
<div class="navbar navbar-inverse">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/" style="padding:15px"><span style="font-size: 1.5em;">Weather.IM</span></a>
	</div>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
        
<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" 
	href="#"> <span class="glyphicon glyphicon-home"></span> </a>
	<ul class="dropdown-menu">
		<li><a href="/">Iowa Environmental Mesonet</a></li>
		<li><a href="https://weather.im">Weather.IM</a></li>
	</ul></li>
        
<?php 
$ar = preg_split('/-/', $THISPAGE);
function get_title($page){
	if (array_key_exists("icon", $page)){
		return sprintf("<div class=\"hidden-sm\">%s<b class=\"caret\"></b></div>"
				."<span class=\"glyphicon glyphicon-%s visible-sm\"></span>",
			$page["title"], $page["icon"] );
	}
	return sprintf("%s<span class=\"caret\"></span>", $page["title"]);
}

while( list($idx, $page) = each($_pages) )
{
  	echo sprintf("<li class=\"dropdown%s\">\n<a class=\"dropdown-toggle\" 
		data-toggle=\"dropdown\" href=\"#\">%s</a>\n", 
      ($ar[0] == $idx) ? " active" : "", get_title($page));

    echo "<ul class=\"dropdown-menu\">\n";
    while( list($idx2, $page2) = each($page["subs"]) )
    {
       echo sprintf("<li><a%s href=\"%s\">%s</a></li>\n", 
         ($ar[1] == $idx2 && $ar[0] == $idx) ? " class=\"active\"" : "",
           $page2["url"],  $page2["title"] );
    }
    echo "</ul>\n</li>\n";
}

  ?>
</ul>
        </div>
      </div>
    </div>
